myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/',views.about ),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.posts_lists, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
]

myproject/users/urls.py
from django.urls import path,include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_user, name="register"),
    path('login/',views.log_in, name="login"),
    path('logout/',views.log_out, name="logout"),
]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner= models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default=None) #on delete tells db how to handle data when user/relationship is deleted. Cascade means, if user gets
    #deleted, all posts will be deleted.

    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','slug','banner']

myproject/myproject/views.py
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Hello, World")
    return render(request, 'home.html')

def about(request):
    # return HttpResponse("About Me")
    return render(request, 'about.html')

myproject/posts/views.py
from django.shortcuts import render,redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def posts_lists(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post= Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})


@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

myproject/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request,'users/register.html', {'form':form})

def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request,form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request,'users/login.html', {'form':form})

def log_out(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

myproject/posts/templates/posts/post_new.html
{% extends "layout.html" %}


{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form class = "form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class='form-submit'>Add Post</button>
</section>

{% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %}


{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
    <section>
        <img class= "banner" src="{{ post.banner.url }}" alt="{{ post.title }}">
    <h1>{{ post.title }}</h1>
            <p>{{ post.date }}</p>
            <p>{{ post.body }}</p>
</section>

{% endblock %}

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}


{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
    <h1>Posts</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                    {{ post.title }}
                </a>
            </h2>
            <p>{{ post.date }} by {{ post.author }} </p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>

{% endblock %}

myproject/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

myproject/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">🏠</a> | 
        <a href="/about">😀</a> | 
        <a href="{% url 'posts:list' %}">📰</a> |
        {% if user.is_authenticated %}
        
            <a href="{% url 'posts:new-post' %}">➕</a>|
            <form class= "logout" action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button class="logout-button">👋</button>
            
        {%else%}
            
            <a href="{% url 'users:register' %}">🚀</a> |
            <a href="{% url 'users:login' %}">🔏</a>
        {%endif%}

        </form>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

myproject/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
Log in
{% endblock %}

{% block content %}
<h1>Log In</h1>
<form class = "form-with-validation" action="{%url 'users:login'%}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    {% endif %}
    <button class='form-submit'>Submit</button>
</form>
{% endblock %}

myproject/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
Register New User
{% endblock %}

{% block content %}
<h1>Register a New User</h1>
<form class = "form-with-validation" action="{%url 'users:register'%}" method="post">
    {% csrf_token %}
    {{ form }}
    <button class='form-submit'>Submit</button>
</form>
{% endblock %}